# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcommand.proto\"b\n\x0fRegisterCommand\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0e\n\x06inet_a\x18\x02 \x01(\x05\x12\x0e\n\x06inet_b\x18\x03 \x01(\x05\x12\x0e\n\x06inet_c\x18\x04 \x01(\x05\x12\x0e\n\x06inet_d\x18\x05 \x01(\x05\x62\x06proto3')



_REGISTERCOMMAND = DESCRIPTOR.message_types_by_name['RegisterCommand']
RegisterCommand = _reflection.GeneratedProtocolMessageType('RegisterCommand', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERCOMMAND,
  '__module__' : 'command_pb2'
  # @@protoc_insertion_point(class_scope:RegisterCommand)
  })
_sym_db.RegisterMessage(RegisterCommand)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERCOMMAND._serialized_start=17
  _REGISTERCOMMAND._serialized_end=115
# @@protoc_insertion_point(module_scope)
