# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\"\x93\x01\n\rUniversalData\x12\x1e\n\x06result\x18\x01 \x01(\x0e\x32\x0e.CommandResult\x12\x31\n\tfail_data\x18\x02 \x01(\x0b\x32\x1e.UniversalData.FailCommandData\x1a/\n\x0f\x46\x61ilCommandData\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xa3\x01\n\x0cRegisterData\x12\x1e\n\x06result\x18\x01 \x01(\x0e\x32\x0e.CommandResult\x12(\n\x04\x66\x61il\x18\x02 \x01(\x0e\x32\x1a.RegisterData.RegisterFail\"I\n\x0cRegisterFail\x12\x12\n\x0eHEARTBEAT_FAIL\x10\x00\x12\x13\n\x0fNOT_SERVER_NODE\x10\x01\x12\x10\n\x0cILLEGAL_INET\x10\x63\"\xad\x02\n\x0fListDevicesData\x12\x1e\n\x06result\x18\x01 \x01(\x0e\x32\x0e.CommandResult\x12.\n\x04\x66\x61il\x18\x02 \x01(\x0e\x32 .ListDevicesData.ListDevicesFail\x12(\n\x07\x64\x65vices\x18\x03 \x03(\x0b\x32\x17.ListDevicesData.Device\x1a\x7f\n\x06\x44\x65vice\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0e\n\x06inet_a\x18\x02 \x01(\x05\x12\x0e\n\x06inet_b\x18\x03 \x01(\x05\x12\x0e\n\x06inet_c\x18\x04 \x01(\x05\x12\x0e\n\x06inet_d\x18\x05 \x01(\x05\x12\x13\n\x0bonline_time\x18\x06 \x01(\x05\x12\x0f\n\x07latency\x18\x07 \x01(\x05\"\x1f\n\x0fListDevicesFail\x12\x0c\n\x08NOT_AUTH\x10\x00*&\n\rCommandResult\x12\x08\n\x04\x46\x41IL\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x62\x06proto3')

_COMMANDRESULT = DESCRIPTOR.enum_types_by_name['CommandResult']
CommandResult = enum_type_wrapper.EnumTypeWrapper(_COMMANDRESULT)
FAIL = 0
SUCCESS = 1


_UNIVERSALDATA = DESCRIPTOR.message_types_by_name['UniversalData']
_UNIVERSALDATA_FAILCOMMANDDATA = _UNIVERSALDATA.nested_types_by_name['FailCommandData']
_REGISTERDATA = DESCRIPTOR.message_types_by_name['RegisterData']
_LISTDEVICESDATA = DESCRIPTOR.message_types_by_name['ListDevicesData']
_LISTDEVICESDATA_DEVICE = _LISTDEVICESDATA.nested_types_by_name['Device']
_REGISTERDATA_REGISTERFAIL = _REGISTERDATA.enum_types_by_name['RegisterFail']
_LISTDEVICESDATA_LISTDEVICESFAIL = _LISTDEVICESDATA.enum_types_by_name['ListDevicesFail']
UniversalData = _reflection.GeneratedProtocolMessageType('UniversalData', (_message.Message,), {

  'FailCommandData' : _reflection.GeneratedProtocolMessageType('FailCommandData', (_message.Message,), {
    'DESCRIPTOR' : _UNIVERSALDATA_FAILCOMMANDDATA,
    '__module__' : 'data_pb2'
    # @@protoc_insertion_point(class_scope:UniversalData.FailCommandData)
    })
  ,
  'DESCRIPTOR' : _UNIVERSALDATA,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:UniversalData)
  })
_sym_db.RegisterMessage(UniversalData)
_sym_db.RegisterMessage(UniversalData.FailCommandData)

RegisterData = _reflection.GeneratedProtocolMessageType('RegisterData', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERDATA,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:RegisterData)
  })
_sym_db.RegisterMessage(RegisterData)

ListDevicesData = _reflection.GeneratedProtocolMessageType('ListDevicesData', (_message.Message,), {

  'Device' : _reflection.GeneratedProtocolMessageType('Device', (_message.Message,), {
    'DESCRIPTOR' : _LISTDEVICESDATA_DEVICE,
    '__module__' : 'data_pb2'
    # @@protoc_insertion_point(class_scope:ListDevicesData.Device)
    })
  ,
  'DESCRIPTOR' : _LISTDEVICESDATA,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:ListDevicesData)
  })
_sym_db.RegisterMessage(ListDevicesData)
_sym_db.RegisterMessage(ListDevicesData.Device)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMANDRESULT._serialized_start=634
  _COMMANDRESULT._serialized_end=672
  _UNIVERSALDATA._serialized_start=15
  _UNIVERSALDATA._serialized_end=162
  _UNIVERSALDATA_FAILCOMMANDDATA._serialized_start=115
  _UNIVERSALDATA_FAILCOMMANDDATA._serialized_end=162
  _REGISTERDATA._serialized_start=165
  _REGISTERDATA._serialized_end=328
  _REGISTERDATA_REGISTERFAIL._serialized_start=255
  _REGISTERDATA_REGISTERFAIL._serialized_end=328
  _LISTDEVICESDATA._serialized_start=331
  _LISTDEVICESDATA._serialized_end=632
  _LISTDEVICESDATA_DEVICE._serialized_start=472
  _LISTDEVICESDATA_DEVICE._serialized_end=599
  _LISTDEVICESDATA_LISTDEVICESFAIL._serialized_start=601
  _LISTDEVICESDATA_LISTDEVICESFAIL._serialized_end=632
# @@protoc_insertion_point(module_scope)
